#!/bin/sh

file="$HOME/.config/BraveSoftware/Brave-Browser/Default/Bookmarks"
#file="$HOME/.config/chromium/Default/Bookmarks"

# exported html, posibly faster

#xml() {
#a=$(xmlstarlet format -H $HOME/.cache/bookmarks_*.html 2>/dev/null |
#    xmlstarlet select -T -t -m '//a' -v 'concat(., ",|", @href)' -n 2>/dev/null \
#    | column -s',' -t | dmenu -i -p 'marcadores web: ' | awk -F'|' '{print $NF}' | tr ' ' '+' )
#
#[ -n "$a" ] && $BROWSER $a
#}
#
#xml

jq -r '.roots[] | recurse(.children?[]?) | select(.type?=="url") | "\(.name)<|\(.url)"' $file \
  | column -s'<' -t| dmenu -i -l 20 -fn 'Mono' -sb '#898818' -p 'marcadores web: ' \
  | awk -F'|' '{print $NF}' | tr ' ' '+' | xargs -r -I{} "$BROWSER" {}

