#!/bin/sh

urlfile=~/.local/share/base
separator='-'
default_se='https://www.google.com/search?q='
#default_se='https://duckduckgo.com/?q='
#default_se='https://www.startpage.com/do/dsearch?query='
#default_se='https://www.bing.com/search?q='

[ -n "$1" ] && case $1 in
	-a|-add) printf '%s' "pon nombre del marcador: " && read -r nombre \
		&& printf '%s' "pon url: " && read -r url && echo "$nombre $separator $url" >> $urlfile;;
	-d|-r) urls=$(fzf --cycle --reverse --prompt='eliminar entrada: ' -m < $urlfile) \
		&& printf '%s\n' "$urls" | while IFS= read -r line
		do
			sed -i "/$line/d" "$urlfile" && notify-send "$line eliminada"
		done;;
	-e|e) "$EDITOR" "$urlfile" ;;
	-H) a="$(sqlite3  ~/.mozilla/firefox/*.defaul*/places.sqlite \
		'SELECT * FROM moz_places;' | tail -n 500 | dmenu -l 20 -fn 'Noto Color Emoj')" && [ -n "$a" ] \
		&& setsid -f "$BROWSER" $(echo $a| cut -d'|' -f2);;
	-b|--bak) bak="$HOME/bak/" && cp $urlfile $bak && notify-send "bakup nuevo en $bak" ;;
	-h|--help|*) printf "opciones son:\\n-add\\n-d (delete entry)\\n-e (edit bookmark file)\\n-H browser history search\\n-b create a backup of bookmarks\\n";;
esac

[ -n "$1" ] && exit

urls=$(grep -v '^#' $urlfile | dmenu -i -l 20 -sb '#898818' -p 'marcadores web:') || exit

if [ -n "$(echo $urls | grep "$separator")" ]; then 
	url=$(printf '%s\n' "$urls" | cut -d"$separator" -f2- |cut -c 2- |tr ' ' '+') 
	pidof -q "$BROWSER" && "$BROWSER" "$url" || setsid -f "$BROWSER" "$url"
else
	url=$(printf '%s\n' "$urls" |tr ' ' '+') 
	pidof -q "$BROWSER" && "$BROWSER" "$default_se$url" \
		|| setsid -f "$BROWSER" "$default_se$url"
fi
